"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useMediaQuery = exports.useDarkMode = exports.useWindowSize = exports.useNotifications = exports.useIdle = exports.useIntersectionObserver = exports.useLocalStorage = exports.useSpeechSynthesis = exports.useFullscreen = exports.useMediaDevices = exports.useNetwork = exports.useClipboard = exports.useGeolocation = exports.useBattery = void 0;
var useBattery_1 = require("./hooks/useBattery");
Object.defineProperty(exports, "useBattery", { enumerable: true, get: function () { return useBattery_1.useBattery; } });
var useGeolocation_1 = require("./hooks/useGeolocation");
Object.defineProperty(exports, "useGeolocation", { enumerable: true, get: function () { return useGeolocation_1.useGeolocation; } });
var useClipboard_1 = require("./hooks/useClipboard");
Object.defineProperty(exports, "useClipboard", { enumerable: true, get: function () { return useClipboard_1.useClipboard; } });
var useNetwork_1 = require("./hooks/useNetwork");
Object.defineProperty(exports, "useNetwork", { enumerable: true, get: function () { return useNetwork_1.useNetwork; } });
var useMediaDevices_1 = require("./hooks/useMediaDevices");
Object.defineProperty(exports, "useMediaDevices", { enumerable: true, get: function () { return useMediaDevices_1.useMediaDevices; } });
var useFullscreen_1 = require("./hooks/useFullscreen");
Object.defineProperty(exports, "useFullscreen", { enumerable: true, get: function () { return useFullscreen_1.useFullscreen; } });
var useSpeechSynthesis_1 = require("./hooks/useSpeechSynthesis");
Object.defineProperty(exports, "useSpeechSynthesis", { enumerable: true, get: function () { return useSpeechSynthesis_1.useSpeechSynthesis; } });
var useLocalStorage_1 = require("./hooks/useLocalStorage");
Object.defineProperty(exports, "useLocalStorage", { enumerable: true, get: function () { return useLocalStorage_1.useLocalStorage; } });
var useIntersectionObserver_1 = require("./hooks/useIntersectionObserver");
Object.defineProperty(exports, "useIntersectionObserver", { enumerable: true, get: function () { return useIntersectionObserver_1.useIntersectionObserver; } });
var useIdle_1 = require("./hooks/useIdle");
Object.defineProperty(exports, "useIdle", { enumerable: true, get: function () { return useIdle_1.useIdle; } });
var useNotifications_1 = require("./hooks/useNotifications");
Object.defineProperty(exports, "useNotifications", { enumerable: true, get: function () { return useNotifications_1.useNotifications; } });
var useWindowSize_1 = require("./hooks/useWindowSize");
Object.defineProperty(exports, "useWindowSize", { enumerable: true, get: function () { return useWindowSize_1.useWindowSize; } });
var useDarkMode_1 = require("./hooks/useDarkMode");
Object.defineProperty(exports, "useDarkMode", { enumerable: true, get: function () { return useDarkMode_1.useDarkMode; } });
var useMediaQuery_1 = require("./hooks/useMediaQuery");
Object.defineProperty(exports, "useMediaQuery", { enumerable: true, get: function () { return useMediaQuery_1.useMediaQuery; } });
